version: '3.8'
services:
  express:
    build: .
    restart: always
    networks:
      - app
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    image: andreygp5/express-rest
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - DB_SCHEMA=${TYPEORM_DATABASE}
      - DB_USER=${TYPEORM_USERNAME}
      - DB_PASSWORD=${TYPEORM_PASSWORD}
      - DB_PORT=${TYPEORM_PORT}

  postgres:
    build: ./postgres/
    restart: always
    networks:
      - app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    image: andreygp5/postgres-rest
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}

networks:
  app:
    driver: bridge
