version: '3.8'
services:
  express:
    build: .
    restart: always
    networks:
      - app
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    image: andreygp5/express-rest
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - DB_SCHEMA=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}

  postgres:
    build: ./postgres/
    restart: always
    networks:
      - app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    image: andreygp5/postgres-rest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  app:
    driver: bridge
